import { PropertyStatus, PropertyType } from "../src/generated/prisma/enums";

export const propertiesData = [
    {
        "title": "Modern Glass Villa",
        "description": "Perched on a private bluff overlooking the Pacific, this Modern Glass Villa is a masterpiece of contemporary architecture. The residence features floor-to-ceiling structural glass walls that blur the line between indoor and outdoor living. Spanning 4,200 square feet, the open-concept floor plan includes a gourmet chef's kitchen with professional-grade appliances, a sprawling master suite with a private terrace, and custom limestone flooring throughout. The exterior is anchored by a zero-edge infinity pool that appears to flow directly into the ocean. Perfect for the discerning buyer seeking ultimate privacy and unparalleled views in the heart of Malibu.",
        "shortDescription": "Luxury oceanfront villa with modern design.",
        "price": 2500000.00,
        "address": "123 Ocean Drive",
        "city": "Malibu",
        "state": "CA",
        "zip": "90265",
        "lat": 34.0259,
        "lng": -118.7798,
        "beds": 5,
        "baths": 4.5,
        "sqft": 4200,
        "lotSize": 0.5,
        "yearBuilt": 2021,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "smart_lighting": true, "energy_efficient": "A+" },
        "tags": ["luxury", "ocean-view", "modern"],
        "highlights": ["Infinity pool", "Home theater", "Private beach access"]
    },
    {
        "title": "Cozy Mountain Cabin",
        "description": "Escape to the tranquility of the Rockies in this authentic log cabin. Tucked away in a dense grove of Aspen pines, this retreat offers a serene atmosphere with high vaulted ceilings and a massive floor-to-ceiling river stone fireplace. The interior features reclaimed wide-plank wood floors and custom cedar cabinetry. After a day on the slopes, relax on the wrap-around redwood deck and enjoy the crisp mountain air. While it feels worlds away, it is only a short drive to Aspen's world-class dining and ski lifts. This cabin is a rare blend of rustic charm and modern accessibility.",
        "shortDescription": "Charming wood cabin in the mountains.",
        "price": 450000.00,
        "address": "789 Pine Way",
        "city": "Aspen",
        "state": "CO",
        "zip": "81611",
        "lat": 39.1911,
        "lng": -106.8175,
        "beds": 2,
        "baths": 1.0,
        "sqft": 1100,
        "lotSize": 1.2,
        "yearBuilt": 1995,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "remote_heating": true },
        "tags": ["rustic", "mountain", "quiet"],
        "highlights": ["Stone fireplace", "Wrap-around deck"]
    },
    {
        "title": "Industrial Downtown Loft",
        "description": "Located in a repurposed 1920s textile factory, this industrial loft epitomizes Brooklyn's urban cool. The unit showcases 14-foot ceilings, original exposed red brickwork, and massive timber beams. Polished concrete floors run throughout the open gallery-style living space, providing the perfect backdrop for art collectors or minimalists. The kitchen is outfitted with stainless steel countertops and a commercial-grade range. Large industrial windows flood the space with natural light and offer views of the historic neighborhood streets. Just steps away from the waterfront and the borough's best coffee shops.",
        "shortDescription": "Trendy urban loft with industrial vibes.",
        "price": 850000.00,
        "address": "456 Factory Ave",
        "city": "Brooklyn",
        "state": "NY",
        "zip": "11201",
        "lat": 40.6925,
        "lng": -73.9903,
        "beds": 1,
        "baths": 1.5,
        "sqft": 1500,
        "type": PropertyType.CONDO,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "voice_control": true },
        "tags": ["urban", "loft", "industrial"],
        "highlights": ["Original brickwork", "Roof access"]
    },
    {
        "title": "Suburban Family Home",
        "description": "This quintessential family residence is situated in one of Austin's most sought-after school districts. The traditional exterior opens into a bright, contemporary interior with a dedicated home office and a large formal dining room. The chef's kitchen features a central island, quartz countertops, and views of the expansive, level backyard—ideal for summer BBQs or a future pool. The primary suite is a private sanctuary with a walk-in closet and a newly renovated spa-like bathroom. With a finished basement and a quiet cul-de-sac location, this home offers plenty of space for growing families.",
        "shortDescription": "Perfect family home in a quiet neighborhood.",
        "price": 625000.00,
        "address": "22 Maple St",
        "city": "Austin",
        "state": "TX",
        "zip": "78701",
        "lat": 30.2672,
        "lng": -97.7431,
        "beds": 4,
        "baths": 3.0,
        "sqft": 2800,
        "lotSize": 0.25,
        "yearBuilt": 2010,
        "type": PropertyType.APARTMENT,
        "status": "SOLD",
        "aiFeatures": {},
        "tags": ["family", "suburban", "backyard"],
        "highlights": ["Finished basement", "Two-car garage"]
    },
    {
        "title": "Sunset Penthouse",
        "description": "The crown jewel of Miami's skyline, this ultra-luxury penthouse offers a lifestyle beyond compare. With over 3,000 square feet of interior space and a massive wrap-around terrace, you can experience sunrises over the Atlantic and sunsets over the Everglades. The unit is finished with rare Calacatta marble, custom Italian cabinetry, and a smart-home system that controls everything from the climate to the automated silk drapery. Residents of Sky Plaza enjoy a dedicated concierge, a rooftop infinity pool, and a private wine cellar. This is high-altitude living for the world's most elite.",
        "shortDescription": "Elite penthouse with premium finishes.",
        "price": 3750000.00,
        "address": "1 Sky Plaza",
        "city": "Miami",
        "state": "FL",
        "zip": "33101",
        "lat": 25.7617,
        "lng": -80.1918,
        "beds": 3,
        "baths": 3.5,
        "sqft": 3100,
        "type": PropertyType.APARTMENT,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "automated_blinds": true, "concierge_ai": true },
        "tags": ["luxury", "penthouse", "miami"],
        "highlights": ["Private elevator", "Outdoor kitchen"]
    },
    {
        "title": "Historical Victorian Mansion",
        "description": "Step back in time with this meticulously preserved Victorian estate in Savannah’s historic district. Known as the 'Rosewood Manor,' this home features grand scale architecture, including soaring 12-foot ceilings, intricate plaster moldings, and original heart pine floors. The grand foyer boasts a hand-carved mahogany staircase, while the seven fireplaces add warmth and character to every room. Modern updates have been seamlessly integrated, including a reinforced foundation and a hidden central cooling system. Surrounded by ancient oak trees draped in Spanish moss, the property includes a private courtyard with a traditional brick pizza oven.",
        "shortDescription": "Historic gem with modern upgrades.",
        "price": 1200000.00,
        "address": "500 Heritage Lane",
        "city": "Savannah",
        "state": "GA",
        "zip": "31401",
        "lat": 32.0809,
        "lng": -81.0912,
        "beds": 6,
        "baths": 4.0,
        "sqft": 5500,
        "lotSize": 0.4,
        "yearBuilt": 1892,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "security_system": "advanced" },
        "tags": ["historic", "mansion", "vintage"],
        "highlights": ["Stained glass", "Wrap-around porch"]
    },
    {
        "title": "Eco-Friendly Tiny House",
        "description": "Experience the ultimate in sustainable living with this cutting-edge tiny house located on the outskirts of Portland. Designed for maximum efficiency, the home features a solar-panel array that powers the entire property, a rain-water collection system, and high-tech spray-foam insulation. The interior is a masterclass in space-saving design, featuring a lofted sleeping area with a skylight for stargazing and a multipurpose living area with hidden storage. Large triple-paned windows offer views of the surrounding forest while maintaining a tight thermal seal. Perfect for the eco-conscious individual looking to minimize their carbon footprint without sacrificing comfort.",
        "shortDescription": "Sustainable tiny home for minimalist living.",
        "price": 120000.00,
        "address": "Trail 9",
        "city": "Portland",
        "state": "OR",
        "zip": "97201",
        "lat": 45.5152,
        "lng": -122.6784,
        "beds": 1,
        "baths": 1.0,
        "sqft": 400,
        "lotSize": 0.1,
        "yearBuilt": 2023,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "solar_optimization": true },
        "tags": ["eco", "minimalist", "tiny-house"],
        "highlights": ["Solar panels", "Composting system"]
    },
    {
        "title": "Lakeside Cottage",
        "description": "Enjoy the classic charm of Lake Tahoe in this beautiful lakefront cottage. Featuring a private wooden dock and a small pebbled beach, this home is built for outdoor recreation. The interior is decorated in a nautical style, with light-washed wood walls and a stone hearth that creates a warm, inviting environment. Large sliding glass doors lead from the living area to a covered patio where you can watch the sunset over the water. The property is surrounded by towering pines, offering both privacy and a deep connection with nature. A perfect summer getaway or a year-round residence for water enthusiasts.",
        "shortDescription": "Beautiful cottage on the lake.",
        "price": 550000.00,
        "address": "88 Lakefront Dr",
        "city": "Lake Tahoe",
        "state": "NV",
        "zip": "89449",
        "lat": 38.9397,
        "lng": -119.9772,
        "beds": 3,
        "baths": 2.0,
        "sqft": 1800,
        "lotSize": 0.3,
        "yearBuilt": 1980,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.PENDING,
        "aiFeatures": {},
        "tags": ["lakefront", "cottage", "serene"],
        "highlights": ["Private dock", "Fire pit"]
    },
    {
        "title": "Minimalist Desert Retreat",
        "description": "This striking modernist home is a dialogue between concrete, steel, and the vast Arizona desert. Designed by a renowned architect, the property utilizes passive solar cooling and thermal mass to stay comfortable in the heat. The minimalist interior features polished concrete floors and a black-steel kitchen that contrasts beautifully with the warm desert sand visible through every window. The property spans five acres, ensuring total solitude and unobstructed views of the starry night sky. Outside, a cantilevered deck provides a shaded area for meditation or evening cocktails. This is more than a home; it is a sanctuary for the soul.",
        "shortDescription": "Modernist architecture in the desert.",
        "price": 980000.00,
        "address": "42 Joshua Tree Rd",
        "city": "Joshua Tree",
        "state": "AZ",
        "zip": "85001",
        "lat": 34.1353,
        "lng": -116.3158,
        "beds": 2,
        "baths": 2.0,
        "sqft": 2000,
        "lotSize": 5.0,
        "yearBuilt": 2019,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "climate_control": "smart" },
        "tags": ["desert", "minimalist", "architecture"],
        "highlights": ["Stargazing deck", "Solar power"]
    },
    {
        "title": "Chic Studio Apartment",
        "description": "Positioned in the heart of Chicago's Loop, this studio apartment is the perfect urban base for a busy professional. The layout has been optimized to maximize every square inch, featuring a Murphy bed that tucks away into custom cabinetry. Large windows overlook the bustling city streets, and the kitchen is equipped with top-tier compact appliances. The building offers 24-hour security, a state-of-the-art fitness center, and a rooftop lounge with fire pits. With a walk score of 98, you are minutes away from the city's best dining, shopping, and public transportation.",
        "shortDescription": "Modern studio for city professionals.",
        "price": 320000.00,
        "address": "101 Metro Ave",
        "city": "Chicago",
        "state": "IL",
        "zip": "60601",
        "lat": 41.8781,
        "lng": -87.6298,
        "beds": 0,
        "baths": 1.0,
        "sqft": 600,
        "type": PropertyType.APARTMENT,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "smart_lock": true },
        "tags": ["studio", "city", "investment"],
        "highlights": ["Gym access", "Near transit"]
    },
    {
        "title": "Classic Brick Rowhouse",
        "description": "This charming Philadelphia rowhouse offers three levels of living space in the historic Queen Village neighborhood. The classic brick facade conceals a modern interior that was fully renovated in 2022. The main floor features an open-concept living and dining area with hardwood floors and a powder room. The second floor houses two bedrooms and a shared bath, while the third floor is dedicated entirely to the primary suite, which leads out to a private rooftop deck with skyline views. The rear of the house features a small, enclosed patio—a rare find in the city—perfect for morning coffee or a small garden.",
        "shortDescription": "Classic urban living in a rowhouse.",
        "price": 725000.00,
        "address": "33 Federal St",
        "city": "Philadelphia",
        "state": "PA",
        "zip": "19147",
        "lat": 39.9526,
        "lng": -75.1652,
        "beds": 3,
        "baths": 2.5,
        "sqft": 2100,
        "yearBuilt": 1920,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": {},
        "tags": ["classic", "rowhouse", "urban"],
        "highlights": ["Roof deck", "Hardwood floors"]
    },
    {
        "title": "Country Equestrian Estate",
        "description": "Nestled in the rolling hills of Kentucky, this world-class equestrian estate is a dream come true for horse lovers. The main residence is a sprawling farmhouse with a wide front porch and expansive living areas. The real star, however, is the professional-grade 6-stall barn equipped with a wash bay, tack room, and automated watering systems. The property includes 15 acres of prime pastureland, a 100x200 foot outdoor riding arena, and several miles of private trails. Whether you are a professional trainer or a hobbyist, this property provides all the infrastructure needed for a high-end equestrian lifestyle.",
        "shortDescription": "Horse property with sprawling land.",
        "price": 1850000.00,
        "address": "1000 Gallop Way",
        "city": "Lexington",
        "state": "KY",
        "zip": "40502",
        "lat": 38.0406,
        "lng": -84.5037,
        "beds": 4,
        "baths": 4.5,
        "sqft": 5000,
        "lotSize": 15.0,
        "yearBuilt": 2005,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "barn_monitoring": true },
        "tags": ["equestrian", "ranch", "land"],
        "highlights": ["6-stall barn", "Fenced pastures"]
    },
    {
        "title": "Beachfront Condo",
        "description": "This stunning beachfront condo in San Diego offers the perfect mix of luxury and convenience. Located directly on the boardwalk, you can enjoy sea breezes and ocean views from your private balcony. The interior has been recently updated with light oak flooring, white quartz countertops, and designer lighting. The building features resort-style amenities, including a beachfront pool, a hot tub, and secure underground parking. Whether you are looking for a vacation home or a permanent residence, this condo offers a rare opportunity to live right on the sand in one of California's most vibrant coastal cities.",
        "shortDescription": "Beachfront living with modern amenities.",
        "price": 790000.00,
        "address": "202 Shoreline Blvd",
        "city": "San Diego",
        "state": "CA",
        "zip": "92101",
        "lat": 32.7157,
        "lng": -117.1611,
        "beds": 2,
        "baths": 2.0,
        "sqft": 1300,
        "type": PropertyType.APARTMENT,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "smart_thermostat": true },
        "tags": ["beach", "condo", "views"],
        "highlights": ["Community pool", "Balcony"]
    },
    {
        "title": "Zen Garden House",
        "description": "Escape the chaos of the city in this architect-designed Zen house in Seattle. The home is built around a central, open-air Japanese courtyard garden featuring a tranquil koi pond and meticulously manicured bonsai trees. The interior uses a palette of natural cedar and stone, with sliding shoji-style doors that allow you to configure the space as needed. A dedicated meditation room and a deep-soaking Japanese tub in the primary bath enhance the peaceful vibe. Large windows provide views of the lush greenery, creating a sense of being in a forest even while in the heart of the city. A true haven for peace and reflection.",
        "shortDescription": "Tranquil home with Zen design.",
        "price": 1150000.00,
        "address": "55 Serenity Way",
        "city": "Seattle",
        "state": "WA",
        "zip": "98101",
        "lat": 47.6062,
        "lng": -122.3321,
        "beds": 3,
        "baths": 2.5,
        "sqft": 2400,
        "lotSize": 0.2,
        "yearBuilt": 2015,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "irrigation_ai": true },
        "tags": ["zen", "garden", "tranquil"],
        "highlights": ["Koi pond", "Soaking tub"]
    },
    {
        "title": "High-Tech Suburban Smart Home",
        "description": "The future of living has arrived in this fully integrated smart home in Silicon Valley. This property is equipped with a centralized AI hub that learns your preferences for lighting, temperature, and music. The kitchen features smart appliances that can suggest recipes based on your fridge inventory, while the Tesla Powerwall provides energy security and efficiency. The layout is designed for modern life, featuring a spacious home office with fiber-optic connectivity and a sound-proofed media room. The outdoor space is just as advanced, with an AI-driven irrigation system and a smart security perimeter. This home is the perfect marriage of luxury and technology.",
        "shortDescription": "The ultimate smart home experience.",
        "price": 895000.00,
        "address": "303 Innovation Dr",
        "city": "San Jose",
        "state": "CA",
        "zip": "95101",
        "lat": 37.3382,
        "lng": -121.8863,
        "beds": 4,
        "baths": 3.5,
        "sqft": 3200,
        "lotSize": 0.18,
        "yearBuilt": 2022,
        "type": PropertyType.HOUSE,
        "status": PropertyStatus.AVAILABLE,
        "aiFeatures": { "full_automation": true, "ai_assistant": "Alexa/Google" },
        "tags": ["smart-home", "tech", "modern"],
        "highlights": ["Tesla Powerwall", "Smart kitchen"]
    }
]