-- AlterEnum
ALTER TYPE "PropertyType" ADD VALUE 'COMMERCIAL';

-- AlterTable
ALTER TABLE "neighborhoods" ALTER COLUMN "zip" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "safetyScore" DROP NOT NULL,
ALTER COLUMN "schoolScore" DROP NOT NULL,
ALTER COLUMN "transitScore" DROP NOT NULL,
ALTER COLUMN "marketTrend" DROP NOT NULL,
ALTER COLUMN "aiAnalysis" DROP NOT NULL,
ALTER COLUMN "expiresAt" DROP NOT NULL;

-- AlterTable
ALTER TABLE "properties" ADD COLUMN     "highlights" TEXT[],
ADD COLUMN     "shortDescription" TEXT,
ALTER COLUMN "lat" DROP NOT NULL,
ALTER COLUMN "lng" DROP NOT NULL,
ALTER COLUMN "baths" SET DATA TYPE DOUBLE PRECISION;
